Parameters:
  BucketName:
    Type: String
    Description: The name of the production S3 bucket

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private
      WebsiteConfiguration:
        IndexDocument: index.html

  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "OAI for accessing the S3 bucket"

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${S3Bucket}/*"
            Principal:
              AWS:
                - !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOAI}"

Outputs:
  S3BucketName:
    Description: "The name of the S3 bucket"
    Value: !Ref S3Bucket
  WebsiteURL:
    Description: "The URL of the website"
    Value: !GetAtt S3Bucket.WebsiteURL
  CloudFrontOAI:
    Description: "The ID of the CloudFront Origin Access Identity"
    Value: !Ref CloudFrontOAI
