name: Deploy React App to AWS S3

env:
  AWS_REGION: us-west-1

on:
  push:
    branches:
      - main
      - development

jobs:
  build:
    name: Build the application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build

  deploy:
    permissions:
      id-token: write
      contents: read

    name: Upload to Amazon S3
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.GH_ACTIONS_ARN }}
          role-duration-seconds: 1800
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy the CloudFormation stack and S3 bucket
        run: |

          # Set DEPLOY_NAME and TEMPLATE_NAME based on the current branch
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            DEPLOY_NAME=rg-portfolio-production
            TEMPLATE_NAME=prod_stack.yml
          elif [[ "${{ github.ref }}" == "refs/heads/development" ]]; then
            DEPLOY_NAME=rg-portfolio-development
            TEMPLATE_NAME=dev_stack.yml
          fi

          # Set the OAI_ID based on the current branch
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            OAI_ID=${{ secrets.OAI_ID }}
          else
            OAI_ID=""
          fi

          # Create or update the CloudFormation stack with the certificate ARN parameter
          aws cloudformation deploy \
            --stack-name "${DEPLOY_NAME}" \
            --template-file "${{ github.workspace }}/.cloudformation/${TEMPLATE_NAME}" \
            --parameter-overrides BucketName="${DEPLOY_NAME}" OriginAccessIdentityID="${OAI_ID}" \
            --no-fail-on-empty-changeset \
            --region "${AWS_REGION}"

          # Sync the build directory to the S3 bucket
          aws s3 sync build/ s3://${DEPLOY_NAME} --delete

      - name: Invalidate CloudFront cache
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |

          # Get the CloudFront distribution ID from secrets
          DISTRIBUTION_ID=${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}

          # Create a new invalidation for all files in the distribution
          INVALIDATION_ID=$(aws cloudfront create-invalidation --distribution-id "${DISTRIBUTION_ID}" --paths "/*" | jq -r '.Invalidation.Id')

          # Wait for the invalidation to complete
          while [[ "$(aws cloudfront get-invalidation --distribution-id "${DISTRIBUTION_ID}" --id "${INVALIDATION_ID}" | jq -r '.Invalidation.Status')" != "Completed" ]]; do
            sleep 10
          done

          # Print a message indicating that the invalidation is complete
          echo "CloudFront invalidation complete (InvalidationId: ${INVALIDATION_ID}) We deployed to production!"
