name: Deploy React App to S3 with IAM Role

on:
  push:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Build the React app
      run: npm run build

  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    needs: build
    
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ secrets.GH_ACTION_ROLE_ARN_ID }}:role/githubActions
        aws-region: us-west-2

    - name: Deploy to Dev S3 with IAM Role
      uses: aws-actions/aws-cli@v1
      env:
        AWS_REGION: us-west-2
      if: github.ref == 'refs/heads/development'
      run: |
        aws s3 sync build s3://my-s3-dev-portfolio-bucket --delete

    - name: Configure AWS credentials from Production account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ secrets.GH_ACTION_ROLE_ARN_ID }}:role/githubActions
        aws-region: us-west-2

    - name: Deploy to Prod S3
      uses: aws-actions/aws-cli@v1
      env:
        AWS_REGION: us-west-2
      if: github.ref == 'refs/heads/main'
      run: |
        aws s3 sync build s3://my-s3-prod-portfolio-bucket --delete