name: Deploy React App to AWS S3

on:
  push:
    branches:
      - main
      - development

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build the React app
        run: npm run build

  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write # required to use OIDC authentication
      contents: read # required to checkout the code from the repo  

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.GH_ACTIONS_ARN }}
          role-duration-seconds: 900 # the ttl of the session, in seconds.
          aws-region: us-west-2 # use your region here.

      - name: Copy files to the dev website with the AWS CLI
        if: github.ref == 'refs/heads/development'
        run: |
          aws s3 sync ./build s3://my-s3-dev-website-bucket --delete

      - name: Copy files to the production website with the AWS CLI
        if: github.ref == 'refs/heads/main'
        run: |
          aws s3 sync ./build s3://my-s3-prod-website-bucket --delete
