name: Deploy React App to AWS S3

on:
  push:
    branches:
      - main
      - development

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build the React app
        run: npm run build

  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.GH_ACTION_ROLE_ARN_ID }}:role/githubActions
          aws-region: us-west-2

      - name: Manual approval for main branch
        id: approve
        uses: actions/manual-approvals@v1
        if: github.ref == 'refs/heads/main'
        with:
          approvals: 1

      - name: Copy files to the test website with the AWS CLI
        if: github.ref == 'refs/heads/development'
        run: |
          aws s3 sync . s3://my-s3-dev-website-bucket

      - name: Copy files to the production website with the AWS CLI
        if: github.ref == 'refs/heads/main'
        run: |
          aws s3 sync . s3://my-s3-prod-website-bucket
