name: Deploy React App to AWS S3

env:
  AWS_REGION: us-west-1
  STACK_NAME: ""

on:
  push:
    branches:
      - main
      - development

jobs:
  build:
    name: Build the application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build

  deploy:
    permissions:
      id-token: write
      contents: read

    name: Upload to Amazon S3
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: build

      - name: Log out build artifact
        run: ls -R build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::195789042358:role/GitHubActions
          role-duration-seconds: 900
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy the CloudFormation stack
        run: |
          if [ "${{ github.ref }}" == "refs/heads/development" ]; then
            STACK_NAME="dev-rg-professional-portfolio-site-v1"
            TEMPLATE_FILE="${{ github.workspace }}/.cloudformation/dev-stack.yml"
          else
            STACK_NAME="prod-rg-professional-portfolio-site-v1"
            TEMPLATE_FILE="${{ github.workspace }}/.cloudformation/prod-stack.yml"
          fi
      
          # Deploy the CloudFormation stack
          aws cloudformation deploy \
            --stack-name $STACK_NAME \
            --template-file $TEMPLATE_FILE \
            --parameter-overrides SiteSuffix=${{ env.STACK_NAME }} \
            --no-fail-on-empty-changeset

      - name: Check if S3 bucket exists and create it if not
        run: |
          S3_BUCKET_NAME="dev-${{ env.STACK_NAME }}"
        
          if ! aws s3api head-bucket --bucket "${S3_BUCKET_NAME}" 2>/dev/null; then
            aws s3api create-bucket \
              --bucket "${S3_BUCKET_NAME}" \
              --region "${AWS_REGION}" \
              --create-bucket-configuration LocationConstraint="${AWS_REGION}"
          fi

      - name: Upload files to the S3 bucket
        run: aws s3 sync build/ s3://${S3_BUCKET_NAME} --delete
